;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        align-cljlet
        cider-repl-return
        cljr-slash
        cljr-splice-sexp-killing-backward
        cljr-slash
        dabbrev-expand
        cljr-splice-sexp-killing-backward
        delete-horizontal-space
        dabbrev-expand
        isearch-forward-regexp
        isearch-other-meta-char
        isearch-printing-char
        delete-horizontal-space
        kill-region
        magit-status
        paredit-backslash
        paredit-backward-kill-word
        paredit-close-curly
        paredit-close-round
        paredit-close-round-and-newline
        paredit-doublequote
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-forward-slurp-sexp
        paredit-kill
        paredit-open-curly
        paredit-open-round
        paredit-wrap-round
        reindent-then-newline-and-indent
        smex
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        cider-load-current-buffer
        isearch-backward-regexp
        isearch-delete-char
        ))
