;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        cljr-slash
        cljr-splice-sexp-killing-backward
        dabbrev-expand
        delete-horizontal-space
        isearch-forward-regexp
        isearch-other-meta-char
        isearch-printing-char
        paredit-backward-kill-word
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-forward-slurp-sexp
        paredit-kill
        paredit-open-round
        paredit-wrap-round
        reindent-then-newline-and-indent
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        ))
