;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        isearch-forward-regexp
        isearch-other-meta-char
        isearch-printing-char
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-kill
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        ))
